# Generated by Django 3.0.3 on 2020-02-28 04:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_seenwork'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heardwork',
            unique_together={('work', 'user')},
        ),
    ]
