# Generated by Django 3.0.3 on 2020-02-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField()),
                ('performers', models.ManyToManyField(to='people.Performer')),
                ('work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='music.Work')),
            ],
        ),
    ]
